export const siteConfigs = {
  title: 'Network State Press',
  heroTitle: ['Network State Press'],
  description:
    'Your Guide to Network States and the technology driving Sovereign Communities',
  keywords: [
    'book club',
    'censorship resistance',
    'citizens',
    'finance',
    'network state',
    'op ed',
    'panarchy',
    'pr',
    'privacy',
    'security',
    'show',
    'technology',
    'update',
    'whistleblower',
  ],
  xHandle: 'logos_state',
  youtubeHandle: ',',
  githubHandle: 'logos-co',
}
